### ISSUE TITLE
Fails on the New Outlook (16.45)

### ISSUE THREAD

**Issue by emilkaae** [josh-h/alfred-search-exchange#1]
I have been using this workflow alot!
Unfortunately, now it has stopped working with the new Outlook (v16.45).

It looks like it breaks down in `hierarchy.applescript` because it cannot get the first item of contacts.

I am guessing `contacts` is null (or similar; I am not familiar with applescript). I am also guessing that it breaks because the UI has changed, and there is no longer a "shared contacts panel". Instead, it looks like one needs to go into Contacts and search there.

I would like to fix the script to make it work again, but I am not sure where to start. Any pointers?

Log from alfred:

> [22:57:06.867] Search Exchange Address Book[Script Filter] Queuing argument 'emil'
> [22:57:07.451] Search Exchange Address Book[Script Filter] Script with argv 'emil' finished
> [22:57:07.461] STDERR: Search Exchange Address Book[Script Filter] ./hierarchy.applescript:300:310: execution error: 
> Microsoft Outlook got an error: Can’t get item 1 of every contact of shared contacts panel. Invalid index. (-1719)

**Comment by josh-h** [comment]
Thank you for using this, I'm glad that you've found it useful. I appreciate the report as well.

It looks like the new Outlook has applescript issues. Running the snippet below doesn't work, the _default account_ property looks like it is not set when using the New Outlook. However, using legacy outlook the variable is set as expected.
 

    on run argv
    	tell application "Microsoft Outlook"
    		set exchange to default account
    		log exchange -- returns 'missing value' when New Outlook is used
    	end tell
    end run


As far as I can tell there is no other way to search exchange from Applescript. If you want to explore the Outlook script API open `Script Editor` then File→Open Dictionary and open `Microsoft Outlook`. That will provide the list of properties that we can call to trigger outlook functions.

I've also reached out to Microsoft support and they directed me to https://outlook.uservoice.com/forums/924856-the-new-outlook-for-mac/suggestions/39253423-support-applescript stating that "AppleScripts are not implemented in the New Outlook".

As an alternative it seems Microsoft now has a graph API that can be used. Sending HTTP get requests like `https://graph.microsoft.com/v1.0/me/people/?$search=emil` might be a better path going forward. You can try their API using their graph explorer https://developer.microsoft.com/en-us/graph/graph-explorer. API docs are here https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0.

I'll experiment with the API and see if I can update the approach. I will welcome your collaboration if you are willing/able to help.

**Comment by emilkaae** [comment]
Hi Josh,

Thanks for your response. I also researched a little further on the topic, and came to the same conclusion regarding the use of AppleScript on the New Outlook. Maybe it will be available once it is ready for general release.

I'll take a look at the graph API. Your input is much appreciated.

Best regards,
Emil
